name             'ruby-rhel'
maintainer       'Danny Knapp'
maintainer_email 'dknapp@salesforce.com'
license          'All rights reserved'
description      'Installs/Configures ruby-rhel'
long_description 'Installs/Configures ruby-rhel'
version          '0.1.0'
